### ISSUE TITLE
Visualizations and dashboards

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincsearch#166]
**Is your feature request related to a problem? Please describe.**
Ability to create visualizations and dashboards

**Describe the solution you'd like**
Ability to create visualizations and dashboards based on the log queries.

**Additional context**
We should discuss on the visualizations that need to be created.
We can start with

1. Histograms
2. Line charts
3. Pie charts
4. Table

Plotly should be a good choice to build visualizations.

**Comment by gedw99** [comment]
Like this one ? 

https://github.com/MetalBlueberry/go-plotly

It would be nicer if the dashboard system has its own api so that different dashboard display frameworks can be layered on top of zinc 

For example sone people need dramatically different outputs from their dashboards.

I use webgl for dashboards often for example to create 3d bar charts and other exotic stuff for ML use cases.

**Comment by prabhatsharma** [comment]
Thanks @gedw99. I was not aware of go-plotly. Will check it out.

**Comment by prabhatsharma** [comment]
Closing this issue. Look at https://github.com/zinclabs/zincsearch/issues/782 for explanation.
