### ISSUE TITLE
Build HA functionality

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincsearch#168]
**Is your feature request related to a problem? Please describe.**
Ability to run in clustered mode to improve HA

**Describe the solution you'd like**
Ability to run in cluster mode.

**Describe alternatives you've considered**

**Additional context**
Ideal way to achieve this would be to do following:
1. Store sharded data in s3
2. Have coordination between nodes using a coordinator like etcd

**Comment by mgenov** [comment]
Maybe it would be better etcd to be replaced with native implementation as it will enforce deployment of an additional components as it's already done in ES. 

It might be better internal RAFT or other consensus protocol to be used for coordination such as: 
https://github.com/hashicorp/raft 
https://github.com/hashicorp/raft-boltdb

**Comment by prabhatsharma** [comment]
I have seen raft earlier. Raft is a viable option if we choose to have stateful storage on disks. In this particular scenario we are looking to store data in s3 and have stateless (only store state temporarily) nodes/pods . This will allow us to scale horizontally a lot easier. I understand the complexity addition by having one more architectural piece in place, but I think etcd in this scenario adds sufficient value.

**Comment by yxw21** [comment]
Looking forward to running in cluster mode

**Comment by gedw99** [comment]
I prefer to use nats for clustering ather than raft directly. NATS itself uses raft-

here is a simple example of using nats to make sqlite HA using the CDC pattern.
https://github.com/maxpert/marmot

The exact same pattern can be using for Zinc 

Its also allows OnPremise  combined with OnCloud topologies because of NATS Leaf node aspects built in.I use this all he time. its awesome
