### ISSUE TITLE
Support for Google Cloud Storage

### ISSUE THREAD

**Issue by jankrynauw** [zinclabs/zincsearch#184]
Are there any plans to support Google Cloud Storage as a storage option, in addition to the current local and S3 storage options?

Looking at the code, one could even consider Google Bigtable as a backend - which should be more performant?

**Comment by theodesp** [comment]
Maybe instead of re-implementing an S3 storage for individual Cloud providers, we should consider using 
[gocloud](https://gocloud.dev/howto/blob/#other-usage-samples). It provides abstractions for blob storage types and supports S3, S3 compatible, GCloud, Azure  or Local Storage.

We may have to change some of the [existing config](https://github.com/zinclabs/zinc/blob/780f731a903aa8b0db78b15129e43f33564bf7b2/pkg/config/config.go#L41-L61) though to allow different providers but the base logic should be the same. 

@prabhatsharma what do you think?

**Comment by prabhatsharma** [comment]
gocloud seems to be awesome. @theodesp Thanks for the reference. Will explore this. Adding this to roadmap.

**Comment by kapillamba4** [comment]
Can i work on this feature?

**Comment by prabhatsharma** [comment]
Please wait. We are re-evaluating how to do this.

**Comment by hengfeiyang** [comment]
Also s3 support is primarily for log search as opposed to app search which is a better use case for zincobserve.

https://github.com/zinclabs/zincobserve
