### ISSUE TITLE
S3 storage

### ISSUE THREAD

**Issue by brycefisher** [zinclabs/zincsearch#2]
I wish I could mashup this project and [quickwit](https://quickwit.io/docs/):

> Quickwit allows true decoupled compute and storage. We designed it to search straight from object storage like AWS S3 in a stateless manner.

I love that `zinc` comes with a Kibana replacement -- a built in UI!

If zinc could also store all its data directly in S3 and decouple storage and compute, you'd have replaced the 99% percent use case of ES/Kibana with a vastly superior technology that is both free as in beer and tshirts, easy to operate, hard to lose data on, and effortless to deploy.

**Comment by Starttoaster** [comment]
> I love that zinc comes with a Kibana replacement -- a built in UI!

I'm glad that you brought that up because having the UI is nice. I do wish that, similar to how ELK stack does it, that the UI for Zinc was its own service that could optionally be ran. This would have multiple benefits to the project:

For one, other people could build their own replacement frontends using whatever API the official frontend uses.

Another benefit is that for people that aren't interested in the frontend at all, or want it to run on a different machine from the actual datastore (Zinc) they could do that.

**Comment by andrewluetgers** [comment]
@Starttoaster and @brycefisher don't forget that EFS is available in AWS Lambda functions https://docs.aws.amazon.com/lambda/latest/dg/services-efs.html

**Comment by prabhatsharma** [comment]
1. S3 would be a good choice for storage. I think we should plan for that in future.
1. s3fs - I have seen multiple incidents where folks burnt their hands with it when used for wrong use case. Would not recommend for this use case.
1. EFS - Not really the right choice for this kind of workload.
1. GUI - Someone looking to build a separate UI should not have a problem as the current UI is just an SPA and actually uses the very same APIs that would be available to anyone else. The reason to have GUI embedded is to get folks easily started with zinc. The decision to embed the UI was based on a [survey on r/elasticsearch](https://www.reddit.com/r/elasticsearch/comments/pvx0us/how_do_you_query_elasticsearch/) on what is it that people use to query elasticsearch and the default UI is the the only one used by most of the folks. Having a separate process for starting just the UI will hurt the user experience of zinc. Also, unlike kibana zinc UI runs completely in the browser with no server side components.

**Comment by landmaj** [comment]
Built-in UI is a killer feature for me. I've been looking for a much simpler ELK which I could use for personal projects for years at this point and Zinc is exactly that. Having to run a separate process for UI would negate half the point. I know people have vastly different use cases than I do but I don't think I'm the only one looking for something easy (single process, no external requirements) and cheap (RAM, CPU) to use. The way the author designed Zinc is exactly what I needed. Thanks!

**Comment by brycefisher** [comment]
Can concur with @landmaj -- same requirements. The ability to leverage s3 for storage would only enhance the utility of zinc for me in the same use case by removing another thing to administer

**Comment by prabhatsharma** [comment]
Released experimental s3 support for zinc today. Binaries can be found at https://github.com/prabhatsharma/zinc/releases/tag/v0.1.4

Docker images at https://gallery.ecr.aws/prabhat/zinc

Would love feedback.

**Comment by chrislusf** [comment]
Zinc is interesting! 

Welcome to integrate with SeaweedFS https://github.com/chrislusf/seaweedfs ! You can use S3 API, or use FUSE mount as a POSIX folder.

**Comment by collimarco** [comment]
> ZincSearch supports S3 and MinIO for index storage. Metadata is still stored on local disk though at this time.

Can you clarify what is the meaning of "index" in this context? Do you refer to all the data (heap) or to the indexes?

Also, what is "metadata"?

**Comment by prabhatsharma** [comment]
e.g. 
data - {"name": "Prabhat Sharma", "city": "San Francisco", "age": 12 }
index - Zinc ingests the above data and creates an index which allows for fast searching.
metadata - name of the index (e.g. - users) , field types - name: text, city: text, age: numeric

**Comment by collimarco** [comment]
Using **S3 as a filesystem looks like an hazard** to me:

- risk of bugs (it's not made for that, you need to re-upload an entire file if a byte changes, concurrency may create issues)
- risk of becoming very expensive since you pay it for every GET, range query, etc.

**What about using S3 for continuous archiving?** e.g. send the new indexes to S3 every couple of minutes (it shouldn't be costly if the indexes are sharded by time and you can send them incrementally) and then have the possibility to download / restore a time range from S3.

**Comment by prabhatsharma** [comment]
Closing due to https://github.com/zinclabs/zincsearch/issues/775 .
