### ISSUE TITLE
Log retention policy: delete old logs automatically

### ISSUE THREAD

**Issue by collimarco** [zinclabs/zincsearch#503]
**Is your feature request related to a problem? Please describe.**
A way to delete automatically the documents after some time (e.g. keep logs only for 3 days, 7 days, 30 days, etc.)

**Describe the solution you'd like**
An option in the admin panel or an environment variable to set a retention policy.

**Describe alternatives you've considered**
I don't know, there should be a simple way to delete older logs, possibly automatically.
It would be also interesting for someone to store older logs on S3 or similar before deleting them, but this can be probably considered a separate feature.

**Additional context**
Most logging services allow to set a duration for logs.

**Comment by tymonx** [comment]
I have also the same request. As temporary workaround I'm planning to create a simple script running as separate independent service running from Docker Compose along with Zinc service. This script will check current disk usage occupied by the Zinc service and use Zinc API to delete the oldest documents to free some space.

Funny, because the ElasticSearch or OpenSearch also don't have built-in retention feature. They are using separate plugin called ISM (Index State Management) that is shipment and enabled with them.

Maybe I may contribute in forward of built-in retention policy in the Zinc.

**Comment by laurivosandi** [comment]
Hi, just to chip in with discussion: In addition to time based retention please add disk size based retention so whatever PV gets allocated to Zinc it will maximally use the allocated space deleting the oldest index once it starts running out of space

**Comment by lezhnev74** [comment]
It looks like this feature is reserved for managed cloud solution, as I see no "removal" methods implemented in the code (no counterpart for `IndexShard::NewShard()`). There is no visible problem to add removal to the code, but it is not there. 

Question to the maintainers, if I pushed a PR with this removal logic (based on size and time), would you consider merging it?

**Comment by prabhatsharma** [comment]
@lezhnev74 This is not really a feature that is reserved for a managed cloud solution as such. zinc is a general purpose search engine. It can be used for log search and app search 2 primary use cases. We believe that log search is the more popular use case for zinc and it requires  deletion of old data based on time or size. We also believe that we can build something much better if we focus on the use case rather than the product. With this thought process we are working to build a product that will specifically cater for log search. It will be an open source solution and we are hoping to release it this month. We should build such a functionality of time/size based deletion in the new tool. 

While zinc can be used for log search, we see its future as specifically being used for app search which does not necessarily benefit from time/size based deletion of data. However if there is a use case for that, I would be more than happy to discuss it and accept a PR.

**Comment by lezhnev74** [comment]
@prabhatsharma thank you for great insights into decision making! It makes total sense. I am looking forward to see the new tool and hopefully use it in our company. 

I'd say that retention policy can be (optionally) applicable to any data, but I have no usecase to support that. In our company we see zinc as a replacement for gigantic ELK stack and use that for log search (retention policy makes a lot of sense here as we are notmally not interested in old logs).

Speaking of retention policy itself. It looks like the easiest way to keep the disk size under control is to delete "old" secondary shards altogether. As we just need to update internal stats and let the system "forget" about that shard and then remove the file on disk.

Applying policy to individual entries across shards leads to shards fragmentation and then merging and cleanup. I wonder how you are going to implement that in the new tool.

**Comment by prabhatsharma** [comment]
closing in favor of https://github.com/zinclabs/zincobserve
